apiVersion: extensions/v1
kind: Deployment
metadata:
  labels:
      service: reverseproxyhima
    name: reverseproxyhima
spec:
  replicas: 1
  template:
    metadata:
      labels:
        service: reverseproxyhima
    spec:
      containers:
      - name: reverseproxyhima
        image: himabharat/simple-express
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 3
          periodSeconds: 3
