apiVersion: v1
kind: Service
metadata:
  labels:
    service: reverseproxyhima
  name: reverseproxyhima-svc
spec:
  ports:
  - name: "8080"
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    service: reverseproxyhima
